# -------------------------------------------------------------------
#  build & deploy pygbag → GitHub Pages
# -------------------------------------------------------------------
name: Build & deploy (pygbag → GitHub Pages)

on:
  push:
    branches: [main]            # run every time main is updated

permissions:
  contents: write               # allow the action to push to gh‑pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ---------------------------------------------------------------
    #  1. checkout repo
    # ---------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------------------------------------------------------------
    #  2. set up python
    # ---------------------------------------------------------------
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ---------------------------------------------------------------
    #  3. cache pip downloads  (optional but speeds up runs)
    # ---------------------------------------------------------------
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('web-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # ---------------------------------------------------------------
    #  4. install web build dependencies
    # ---------------------------------------------------------------
    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        pip install -r web-requirements.txt

    # ---------------------------------------------------------------
    #  5. build WASM bundle
    # ---------------------------------------------------------------
    - name: Build web bundle with pygbag
      run: |
        pygbag --build --ume_block 0 --title "Jovian Front" main.py
        # Flip autorun so the game starts without a click
        sed -i 's/autorun[[:space:]]*:[[:space:]]*0/autorun : 1/' build/web/index.html

    # ---------------------------------------------------------------
    #  6. deploy build/web → gh‑pages branch
    # ---------------------------------------------------------------
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
