# .github/workflows/build-and-deploy.yml
name: build & deploy pygbag → GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: write        # let the action push gh‑pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: install *latest* pygbag
      # ↑ pulls straight from the repo’s main branch
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/pygame-web/pygbag.git

    - name: build web bundle
      run: pygbag --build --ume_block 0 main.py

    - name: deploy to pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
